workflows:
  android-workflow:
    name: Android Workflow

    max_build_duration: 120

    environment:
      vars:
        PACKAGE_NAME: "com.example.medicinereminder"

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk